"""add table github_repos, github_user_stats and github_user_dynamic_stats

Revision ID: 51e6450eb111
Revises: d87f41f2c579
Create Date: 2023-01-10 17:01:50.045120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e6450eb111'
down_revision = 'd87f41f2c579'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_repos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('language', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_user_dynamic_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_login', sa.String(length=255), nullable=True),
    sa.Column('dimension', sa.String(length=255), nullable=True),
    sa.Column('int_value', sa.Integer(), nullable=True),
    sa.Column('str_value', sa.String(length=255), nullable=True),
    sa.Column('json_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_login', sa.String(length=255), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('starred_count', sa.Integer(), nullable=True),
    sa.Column('repo_count', sa.Integer(), nullable=True),
    sa.Column('public_repo_count', sa.Integer(), nullable=True),
    sa.Column('public_gist_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_user_stats')
    op.drop_table('github_user_dynamic_stats')
    op.drop_table('github_repos')
    # ### end Alembic commands ###
