"""add company to github_user_stats

Revision ID: 90821042d43e
Revises: d0cdfea2e767
Create Date: 2023-01-12 10:37:23.342173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90821042d43e'
down_revision = 'd0cdfea2e767'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_user_stats', sa.Column('company', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_user_stats', 'company')
    # ### end Alembic commands ###
