"""add commit_sha to github_events

Revision ID: cc9f8816d536
Revises: 90821042d43e
Create Date: 2023-01-12 10:40:34.611991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9f8816d536'
down_revision = '90821042d43e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_events', sa.Column('commit_sha', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_events', 'commit_sha')
    # ### end Alembic commands ###
