"""add colums to github_events

Revision ID: d0cdfea2e767
Revises: fbefe3295dd2
Create Date: 2023-01-11 18:14:51.012240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0cdfea2e767'
down_revision = 'fbefe3295dd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_events', sa.Column('node_id', sa.String(length=255), nullable=True))
    op.add_column('github_repos', sa.Column('star_count', sa.Integer(), nullable=True))
    op.add_column('github_repos', sa.Column('fork_count', sa.Integer(), nullable=True))
    op.add_column('github_repos', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('github_repos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('github_repos', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_repos', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('github_repos', 'created_at')
    op.drop_column('github_repos', 'updated_at')
    op.drop_column('github_repos', 'fork_count')
    op.drop_column('github_repos', 'star_count')
    op.drop_column('github_events', 'node_id')
    # ### end Alembic commands ###
