"""add column event_source in github_events

Revision ID: d87f41f2c579
Revises: c8a357f2db6b
Create Date: 2023-01-06 20:13:52.822307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87f41f2c579'
down_revision = 'c8a357f2db6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_events', sa.Column('event_source', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_events', 'event_source')
    # ### end Alembic commands ###
