"""add new columns for github_events

Revision ID: fbefe3295dd2
Revises: 51e6450eb111
Create Date: 2023-01-10 17:51:31.796027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbefe3295dd2'
down_revision = '51e6450eb111'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_events', sa.Column('action', sa.String(length=255), nullable=True))
    op.add_column('github_events', sa.Column('additions', sa.Integer(), nullable=True))
    op.add_column('github_events', sa.Column('deletions', sa.Integer(), nullable=True))
    op.add_column('github_events', sa.Column('changed_files', sa.Integer(), nullable=True))
    op.add_column('github_events', sa.Column('pr_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_events', 'pr_number')
    op.drop_column('github_events', 'changed_files')
    op.drop_column('github_events', 'deletions')
    op.drop_column('github_events', 'additions')
    op.drop_column('github_events', 'action')
    # ### end Alembic commands ###
